### ISSUE TITLE
Chunking CSV file

### ISSUE THREAD

**Issue by Eth3rnit3** [patterns-ai-core/langchainrb#549]
### Problem:
When attempting to parse CSV files using the gem, an error occurs due to improper handling of text chunking.

```ruby
file_path       = 'data/folder/test.csv'
abs_path        = File.expand_path(file_path)

llm = Langchain::LLM::OpenAI.new(api_key: ENV['OPEN_AI_KEY'])
db = Langchain::Vectorsearch::Chroma.new(
  url: ENV['CHROMA_DB_URL'],
  index_name: ENV.fetch('CHROMA_DB_INDEX_NAME', 'documents'),
  llm:
)
db.add_data(paths: [Langchain.root.join(abs_path)], options: { col_sep: ';' })
```

It raise following error
```shell
splits = separator.empty? ? text.chars : text.split(separator)
                                                   ^^^^^^
from /Users/david/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/baran-0.1.11/lib/baran/text_splitter.rb:21:in `chunks'
from /Users/david/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/langchainrb-0.10.2/lib/langchain/chunker/text.rb:33:in `chunks'
from /Users/david/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/langchainrb-0.10.2/lib/langchain/data.rb:26:in `chunks'
from /Users/david/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/langchainrb-0.10.2/lib/langchain/vectorsearch/base.rb:189:in `block in add_data'
from /Users/david/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/langchainrb-0.10.2/lib/langchain/vectorsearch/base.rb:188:in `map'
from /Users/david/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/langchainrb-0.10.2/lib/langchain/vectorsearch/base.rb:188:in `add_data'
from test.rb:12:in `<main>'
```

### Context:

The error arises within the Langchain::Vectorsearch::Chroma module when processing CSV files. The current implementation fails to accommodate arrays of strings, such as those generated by reading CSV files, leading to the TypeError mentioned above.

**Comment by Eth3rnit3** [comment]
I can confirm that the problem has been corrected 👍 well done guys for all your hard work!

**Comment by andreibondarev** [comment]
Thank you to @WToa !
